"""Add token_type field to device_tokens table

Revision ID: 1c6c6773cc67
Revises: 16c9d276ddbd
Create Date: 2025-07-17 21:34:23.225657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6c6773cc67'
down_revision = '16c9d276ddbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_type', sa.String(length=20), nullable=True))
    
    # Update existing rows to set default value
    op.execute("UPDATE device_tokens SET token_type = 'expo' WHERE token_type IS NULL")
    
    # Make column NOT NULL
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.alter_column('token_type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_column('token_type')

    # ### end Alembic commands ###
